LABEL org.opencontainers.image.source=https://github.com/boomerlen/desn2k
LABEL org.opencontainers.image.description="Simple Python requests image"
LABEL org.opencontainers.image.licences=MIT

FROM python:slim

RUN python -m pip install requests

CMD ["/bin/bash"]
