name: build-docs
on:
  push:
    paths:
      - 'docs/'
jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: ghcr.io/boomerlen/docs-container:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy docs 
        run: mkdocs gh-deploy
