name: build-push-python-reqs-container
on:
  push:
    branches: ['main']
    paths:
      - 'Docs/Dev/Dockerfile'
  pull_request:
    types: [opened, synchronize]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: python-reqs
jobs:
  build-python-reqs-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GH container reg 
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          file: ./Docs/Dev/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
