name: export-docs
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'Docs/**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: python-reqs
jobs:
  build-python-reqs-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: '${{GITHUB_WORKSPACE}/Docs/Dev/Dockerfile'
    
  export-docs-png:
    runs-on: ubuntu-latest
    container: ' ${{GITHUB_WORKSPACE}}/Docs/Dev/Dockerfile '
    services:
      drawio-export:
        image: jgraph/drawio-export
        ports:
          - 8000:8000

